FROM python:3.4-onbuild

RUN ls /usr/src/app/urlshortener/static/img
RUN ls /usr/src/app/urlshortener/static/js/
COPY urlshortener/static/ /usr/src/app/urlshortener/static/
RUN ls /usr/src/app/urlshortener/static/img
RUN ls /usr/src/app/urlshortener/static/css
